GET http://localhost:3000/

###
POST http://localhost:3000/api/wilder/create HTTP/1.1
content-type: application/json


###

GET http://localhost:3000/api/wilder/read

###
GET http://localhost:3000/api/wilder/read/6228bca9555685a128dad293ss

###
PUT http://localhost:3000/api/wilder/update/6228bca9555685a128dad293 HTTP/1.1
content-type: application/json

{

    "skills": [
    {
        "title": "HTML 5",
        "votes": 10,
        "_id": "622719d2a67b24a36a65dabc"
    },
    {
        "title": "REACT",
        "votes": 4
    }
    ]
}

###

DELETE http://localhost:3000/api/wilder/delete/6228bca9555685a128dad293 HTTP/1.1

###

GET http://localhost:3000/testouille
